name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>USER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          git config --global user.email "grigoryr@liveperson.com"
          git config --global user.name "grigoryr"
          mvn -B clean release:clean release:prepare release:perform -Dbuildtype=release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

